mujoco_server:
  ros__parameters:
    cam_config:
      fixed_cam:
        stream_type: 1
        frequency: 30
      left_arm_cam:
        stream_type: 1
        frequency: 30
      right_arm_cam:
        stream_type: 1
        frequency: 30