#!/usr/bin/env python3
import sys
import os
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float64MultiArray
import numpy as np

# Add the parent directory of 'oscbf' to the Python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../oscbf')))

try:
    import jax
    import jax.numpy as jnp
    from cbfpy import CBF
    from oscbf.core.manipulator import load_panda
    from oscbf.examples.dynamic_motion import EESafeSetVelocityConfig
except ImportError as e:
    print(f"Failed to import oscbf or JAX modules: {e}")
    sys.exit(1)

class OscbfPoseFilterNode(Node):
    def __init__(self):
        super().__init__('oscbf_pose_filter')
        # Subscribes to the raw Cartesian desired poses generated by key_pub.py
        self.subscription = self.create_subscription(
            Float64MultiArray,
            '/multi_cartesian_impedance/oscbf_request',
            self.listener_callback,
            10)
        # Publishes the filtered/safe Cartesian desired poses back to the impedance controller
        self.publisher = self.create_publisher(
            Float64MultiArray, 
            '/multi_cartesian_impedance/pose_desired', 
            10)
            
        # Initialize basic workspace bounds for limiting EE Cartesian desired poses
        self.robot = load_panda()
        
        # OSCBF config containing our end effector boundaries
        pos_min = (0.25, -0.4, 0.25)
        pos_max = (0.65,  0.4, 0.65)
        self.config = EESafeSetVelocityConfig(self.robot, pos_min, pos_max)
        
        self.get_logger().info('OSCBF Pose Target Filter Node Started. Intercepting poses from key_pub.py...')
        
    def listener_callback(self, msg):
        data = np.array(msg.data)
        out_msg = Float64MultiArray()
        safe_data = []
        
        # each arm has 12 elements (3 pos + 9 rot)
        num_arms = len(data) // 12
        for i in range(num_arms):
            start_idx = i * 12
            
            target_pos = data[start_idx : start_idx + 3]
            target_rot = data[start_idx + 3 : start_idx + 12]
            
            # Since OSCBF is a Torque/Velocity controller safety filter, 
            # treating Pose values with a direct projection onto safe Cartesian space.
            # (If you need proper control-level CBF you should apply it down in cpp or via Twist command inputs)
            clipped_pos = np.clip(target_pos, self.config.pos_min, self.config.pos_max)
            
            safe_data.extend(clipped_pos.tolist())
            safe_data.extend(target_rot.tolist())

        out_msg.data = safe_data
        self.publisher.publish(out_msg)

def main(args=None):
    rclpy.init(args=args)
    node = OscbfPoseFilterNode()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()