/**:
  ros__parameters:
    qos_overrides:
      /mujoco_server/cameras/left_arm_cam/rgb/image_raw:
        subscription:
          reliability: best_effort
          depth: 1
      /mujoco_server/cameras/right_arm_cam/rgb/image_raw:
        subscription:
          reliability: best_effort
          depth: 1
      /mujoco_server/cameras/fixed_cam/rgb/image_raw:
        subscription:
          reliability: best_effort
          depth: 1
